### ISSUE TITLE
Specify portname doesn't work

### ISSUE THREAD

**Issue by lhondareyte** [hselasky/jack_umidi#1]
Not sure this an issue or an misunderstanding, but I can not change registered name in `jackd`. On FreeBSD 12: 
```
root@unxbox:~ # jack_umidi -d /dev/umidi0.0 -B`
root@unxbox:~ # jack_lsp
...
Midiman Midispor #0:midi.TX
Midiman Midispor #0:midi.RX
```
The same, specify portname
```
root@unxbox:~ # jack_umidi -d /dev/umidi0.0 -n "foo" -B
root@unxbox:~ # jack_lsp
...
system:playback_2
Midiman Midispor #0:midi.TX
Midiman Midispor #0:midi.RX 
```
Regards,
Luc

**Comment by hselasky** [comment]
Hi,

Do you already have a jack_umidi instance running?

ps auxw | grep jack_umidi

--HPS

**Comment by lhondareyte** [comment]
Hi,
Thanks for your fast reply. No, there is only one instance of `jack_umidi`. I run `jackd` with the following options:
```
jackd -ddummy -r 
```
But it's the same with default options:
```
/usr/local/bin/jackd -r -doss -r48000 -p128 -n3 -w16
```

**Comment by lhondareyte** [comment]
The `-A`option is omited for `jack_lsp` in my posts, but the result is the same.

**Comment by hselasky** [comment]
Can you try this patch:
https://github.com/hselasky/jack_umidi/commit/d8caac12dfa003a53cc965d94f657e2160601611

--HPS

**Comment by hselasky** [comment]
The fix will be part of the next jack_umidi release.
