### ISSUE TITLE
Failed to add device via devd on startup

### ISSUE THREAD

**Issue by lhondareyte** [hselasky/jack_umidi#2]
Hello,
`jack_umidi` fails on startup via `devd` because `jackd` is not running yet. I need to replug the interface to make it works again.
I [wrote a dirty hack ](https://github.com/lhondareyte/jack_umidi/commit/d1e1d8f98556f89ac22da8694ff5d7f4a87a949a)to add a timeout on startup (4s is sufficient in my case) to wait for `jackd`. It works for me but maybe there is an better solution.
Regards

**Comment by hselasky** [comment]
https://svnweb.freebsd.org/ports?view=revision&revision=529277

Fix is now submitted upstream.

Thank you!
